--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
-- Dumped by pg_dump version 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sales_salesuser; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.sales_salesuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(50) NOT NULL,
    group_leader_id bigint
);


ALTER TABLE public.sales_salesuser OWNER TO myuser;

--
-- Name: sales_salesuser_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.sales_salesuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_salesuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: sales_salesuser; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (36, 'pbkdf2_sha256$870000$OouzWk0AVoCtW7khzv156b$GGq9vg4ShN3s4CnR/xlW5zsSu6aJ8HSFG4KYmOw5KK8=', NULL, false, '刘永林', '永林', '刘', '', false, true, '2024-10-21 11:40:00+08', 'user', 8);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (37, 'pbkdf2_sha256$870000$pIY9mbrzCHyNYyVOf9fjdI$TKGP9DSxcAe+DI9qaEQXcg29sixG8a5uQnfSuPy1Hn4=', NULL, false, '张海玲', '海玲', '张', '', false, true, '2024-10-21 11:40:00+08', 'user', 8);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (8, 'pbkdf2_sha256$870000$pqOlyY1OvwVFQZ5ShETz52$39kbIGql88SXN2UGNXqxTCGqzN7ZtUD2hDww+xnEow0=', '2024-10-08 15:20:00+08', true, '董婷婷', '', '', '', true, true, '2024-10-08 15:19:00+08', 'admin', NULL);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (13, 'pbkdf2_sha256$870000$jhwgqdD1yrienoIR5QoVwO$dL62ioA0rE0oN88cEw5l7DeekmivKioBZLUEMBux7Ts=', NULL, false, '胡夏阳', '夏阳', '胡', '', false, true, '2024-10-08 17:44:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (18, 'pbkdf2_sha256$870000$yI5DxqiL7dLA4rtX4CXgS7$03N6wfXqpWZZfIN/2o4jOKsfwzw8beD9jZg6WBiYWUg=', NULL, false, '魏豪', '豪', '魏', '', false, true, '2024-10-08 17:58:00+08', 'user', 8);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (17, 'pbkdf2_sha256$870000$JjY2sodYChYgQGMA4PNrR5$uE3Hhv/kNLV80IYE4KWeEITSLcM1MsxP5mbEAUN3HmE=', NULL, false, '张俊', '', '', '', false, true, '2024-10-08 17:56:00+08', 'user', 13);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (19, 'pbkdf2_sha256$870000$1wsenE5w4D7e6hn2G83wV6$p5O1o5KjQhPF2B/i7PuNIkNySAqV/3F+U5Wa3NMw+NE=', NULL, false, '吴小维', '', '', '', false, true, '2024-10-08 17:58:00+08', 'user', 13);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (29, 'pbkdf2_sha256$870000$eOljSCGkeG8yePZBigmTik$nFP1KmjWzkbUvA9EtoVWW/SpdkU80E7gYKPIGTRrB+k=', '2024-10-08 18:09:00+08', true, '陈予琳', '', '', '', true, true, '2024-10-08 18:08:00+08', 'admin', NULL);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (11, 'pbkdf2_sha256$870000$cswbCthoCO3nIbvjKz7z5Y$/1s2/ZPzkS1LOyCOepQ6idbpTxdQiHArXtqyqF5BMQ8=', NULL, false, '晴妹', '', '', '', false, true, '2024-10-08 15:44:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (20, 'pbkdf2_sha256$870000$3Sb0Xv9dp3u9Ybr461qTth$WzTGRVL/P97I2w2ZUBGUJn1x+kf/zL7o4kvC1sHl05U=', NULL, false, '邓小亮', '小亮', '邓', '', false, true, '2024-10-08 17:59:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (24, 'pbkdf2_sha256$870000$q91psXQvlsE72c66Ms0E5q$McRxmZWEC2n7Z1QNsu0uKSpuTxh8652vXKQkmPsiGBs=', NULL, false, '张凯钦', '凯钦', '张', '', false, true, '2024-10-08 18:04:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (33, 'pbkdf2_sha256$870000$oyr3GePvIyLdsLrxY08V92$WYpucafivYcMj5wxLyDL2mvKMUocd/dnW3A4x8qSQx4=', NULL, false, '丁丽婷', '丽婷', '丁', '', false, true, '2024-10-21 09:20:00+08', 'user', 8);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (34, 'pbkdf2_sha256$870000$PjRQSrT6iALwtbLT6Qw04H$6uSwKARsnVh7OKqTGEq9Ut5kwwF8U2UV1cFut8TlR5c=', NULL, false, '陈怡君', '怡君', '陈', '', false, true, '2024-10-21 09:21:00+08', 'user', 8);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (28, 'pbkdf2_sha256$870000$39MPOANk52gOQcL8sv4hSF$QyEG/kzSA3+u4YxTiKOHy2SSWQU0wrdYD+pxT+oKWVA=', NULL, false, '朱龙冲', '龙冲', '朱', '', false, true, '2024-10-08 18:07:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (32, 'pbkdf2_sha256$870000$410roo58N8xi97vQX29bxJ$rnv1lSfza/48gUK/RXUloNgGB3oLCLgxINiajg3oiWU=', NULL, true, '任侠', '', '', '', true, true, '2024-10-18 19:17:00+08', 'admin', NULL);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (31, 'pbkdf2_sha256$870000$7oufIssUaFv3oRKlMxiZUk$kaYcBJbwBrrei/o8+4ZMoB8Ai+SH7BU4Wz/kvD9DDeY=', NULL, false, '丁雨波', '', '', '', false, true, '2024-10-08 18:40:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (14, 'pbkdf2_sha256$870000$FWQWJH0umYi71VPkIyItfL$5EzvbSPScqkbQRJobPKp96WkDl38C0Mrkr8fObeykb4=', NULL, false, '秦嘉豪', '嘉豪', '秦', '', false, true, '2024-10-08 17:47:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (26, 'pbkdf2_sha256$870000$eiceeQNu3zUmBKfiZs6wu5$uJpFtzJkBCQQvVIUmOiOV7lw2DD5O86Z2EdfFarmnSM=', NULL, false, '胡小婷', '小婷', '胡', '', false, true, '2024-10-08 18:05:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (27, 'pbkdf2_sha256$870000$qSFZBT8gBySVRIiA6PU9bf$sA3ZcQMtRk/AnkdIEoJoe8lL5s9XaPdgAleSDXpaR14=', NULL, false, '邹敏', '敏', '邹', '', false, true, '2024-10-08 18:06:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (35, 'pbkdf2_sha256$870000$7uLnE55o2KLt8mWBYBFkUJ$aqdfVGr/jdIrHExqace4xKlRcMBXH79ANTqag8BKACo=', NULL, false, '金坤香', '坤香', '金', '', false, true, '2024-10-21 09:46:00+08', 'user', 8);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (22, 'pbkdf2_sha256$870000$XfBwj7Za5O5Dnab3dR75LG$IgN1fwwBpkvFAG4pMdgmuRaCD+QAOocJo5tGW+62Jek=', NULL, false, '李小伟', '小伟', '李', '', false, true, '2024-10-08 18:01:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (6, 'pbkdf2_sha256$870000$DFSLyNbhLWrZox5qX4ovzQ$mRZcxUHtti06zyZTKfFCVdtRyeZrPVrumOkue1jp0Qk=', NULL, false, '李美钰', '美钰', '李', '', false, true, '2024-10-08 14:29:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (25, 'pbkdf2_sha256$870000$riD6v1RwaunQV9MLTpXmIC$rFrlQxmkWHKk6VCOXGDp881bN7fQnwQ5draVie3cF80=', NULL, false, '王微伟', '微伟', '王', '', false, true, '2024-10-08 18:05:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (1, 'pbkdf2_sha256$600000$UQc85lxlcFKZqgPtQY1fna$3D6roZSy3c7kz4godiO5O/v17R3wjPX1DduvV+SETyg=', '2024-11-13 15:25:55.048925+08', true, 'austin', '', '', '', true, true, '2024-10-06 18:40:00+08', 'admin', NULL);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (2, 'pbkdf2_sha256$870000$PVTeNm0I5BUPwRJo4ZP5ii$PJFz5l5LywzEeYTgSr5lCR/qfuHtQwGz44dzCUVAg9c=', '2024-11-10 23:19:48.271493+08', false, '冷子慧', '子慧', '冷', '', false, true, '2024-10-08 10:10:00+08', 'user', 4);
INSERT INTO public.sales_salesuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, group_leader_id) VALUES (4, 'pbkdf2_sha256$870000$KKJCCREAqnwAahYOmmjuxS$0tYIQkAQuFL9YdCWRlHMNXmDo3R27fALkMmcvBdUwvA=', '2024-11-10 23:27:03.482475+08', false, '汪城波', '', '', '', false, true, '2024-10-08 14:17:00+08', 'group_leader', 4);


--
-- Name: sales_salesuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.sales_salesuser_id_seq', 37, true);


--
-- Name: sales_salesuser sales_salesuser_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.sales_salesuser
    ADD CONSTRAINT sales_salesuser_pkey PRIMARY KEY (id);


--
-- Name: sales_salesuser sales_salesuser_username_key; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.sales_salesuser
    ADD CONSTRAINT sales_salesuser_username_key UNIQUE (username);


--
-- Name: sales_salesuser_group_leader_id_f0a00161; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX sales_salesuser_group_leader_id_f0a00161 ON public.sales_salesuser USING btree (group_leader_id);


--
-- Name: sales_salesuser_username_1911959e_like; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX sales_salesuser_username_1911959e_like ON public.sales_salesuser USING btree (username varchar_pattern_ops);


--
-- Name: sales_salesuser sales_salesuser_group_leader_id_f0a00161_fk_sales_salesuser_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.sales_salesuser
    ADD CONSTRAINT sales_salesuser_group_leader_id_f0a00161_fk_sales_salesuser_id FOREIGN KEY (group_leader_id) REFERENCES public.sales_salesuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

