# Generated by Django 4.2.16 on 2025-01-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0023_alter_recording_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('source_channel', models.CharField(max_length=50, verbose_name='来源渠道')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('education', models.CharField(max_length=50, verbose_name='学历')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('employment_status', models.CharField(max_length=50, verbose_name='就业情况')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('employment_teacher', models.CharField(max_length=100, verbose_name='就业老师')),
                ('follow_up', models.TextField(verbose_name='跟进记录')),
                ('issues', models.TextField(verbose_name='存在问题')),
                ('solutions', models.TextField(verbose_name='解决办法')),
                ('remarks', models.TextField(default='无', verbose_name='备注')),
                ('deal_status', models.CharField(max_length=50, verbose_name='成交情况')),
                ('payment_method', models.CharField(max_length=50, verbose_name='支付方式')),
                ('payment_amount', models.FloatField(verbose_name='支付金额')),
                ('client_summary', models.TextField(verbose_name='客户总结')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='客户')),
            ],
        ),
    ]
