# Generated by Django 4.2.16 on 2025-01-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0002_alter_clientdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='client_summary',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='deal_status',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='employment_teacher',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='source_channel',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='analysis',
            field=models.TextField(blank=True, default='未知', null=True, verbose_name='情况分析'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='employment_details',
            field=models.TextField(blank=True, default='未知', null=True, verbose_name='具体就业情况'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='feedback',
            field=models.TextField(blank=True, default='未知', null=True, verbose_name='问题反馈'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='报名日期'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='sales_teacher',
            field=models.CharField(blank=True, default='未知', max_length=100, null=True, verbose_name='销售老师'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='study_progress',
            field=models.CharField(blank=True, default='未知', max_length=100, null=True, verbose_name='学习进度'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='study_time',
            field=models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='学习时间'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='education',
            field=models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='employment_status',
            field=models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='就业情况'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='gender',
            field=models.CharField(blank=True, default='未知', max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='major',
            field=models.CharField(blank=True, default='未知', max_length=100, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='payment_method',
            field=models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='phone',
            field=models.CharField(blank=True, default='未知', max_length=20, null=True, verbose_name='电话'),
        ),
    ]
