# Generated by Django 4.2.16 on 2025-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0003_remove_clientdata_client_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='feedback',
            field=models.TextField(blank=True, default='无反馈', null=True, verbose_name='问题反馈'),
        ),
    ]
