# Generated by Django 4.2.16 on 2025-01-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0004_alter_clientdata_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
    ]
