# Generated by Django 4.2.16 on 2025-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0005_alter_clientdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='customer_summary',
            field=models.TextField(blank=True, default='无', null=True, verbose_name='客户总结'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='deal_status',
            field=models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='成交情况'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='is_employed',
            field=models.CharField(blank=True, default='未知', max_length=10, null=True, verbose_name='是否就业'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='支付金额'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='payment_method_detail',
            field=models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='problem_exists',
            field=models.TextField(blank=True, default='无', null=True, verbose_name='存在问题'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='remarks',
            field=models.TextField(blank=True, default='无', null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='responsible_person',
            field=models.CharField(blank=True, default='未知', max_length=100, null=True, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='solution',
            field=models.TextField(blank=True, default='无', null=True, verbose_name='解决办法'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='age',
            field=models.CharField(blank=True, default='未知', max_length=10, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='payment_method',
            field=models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='sales_teacher',
            field=models.CharField(blank=True, default='未知', max_length=100, null=True, verbose_name='就业老师'),
        ),
    ]
