# Generated by Django 4.2.16 on 2025-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0007_alter_clientdata_age_alter_clientdata_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='employment_details',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='is_employed',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='payment_method_detail',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='study_progress',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='study_time',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='follow_up_record',
            field=models.TextField(blank=True, null=True, verbose_name='跟进记录'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='source_channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='来源渠道'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
    ]
