# Generated by Django 4.2.16 on 2025-01-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0009_alter_clientdata_options_alter_clientdata_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='is_employed_after_study',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否'), ('未知', '未知')], max_length=10, null=True, verbose_name='是否学完就业'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='problem_tracking',
            field=models.TextField(blank=True, null=True, verbose_name='问题追踪'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='situation_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='情况分析'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='study_progress',
            field=models.TextField(blank=True, null=True, verbose_name='学习进度'),
        ),
    ]
