# Generated by Django 4.2.16 on 2025-01-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0010_clientdata_is_employed_after_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女'), ('未知', '未知')], max_length=20, null=True, verbose_name='性别'),
        ),
    ]
