# Generated by Django 4.2.16 on 2025-01-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0011_alter_clientdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='deal_status',
            field=models.CharField(blank=True, choices=[('已成交', '已成交'), ('未成交', '未成交'), ('跟进中', '跟进中'), ('未知', '未知')], max_length=150, null=True, verbose_name='成交情况'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='education',
            field=models.CharField(blank=True, choices=[('小学', '小学'), ('初中', '初中'), ('高中', '高中'), ('大专', '大专'), ('本科', '本科'), ('研究生及以上', '研究生及以上'), ('未知', '未知')], max_length=150, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('在职', '在职'), ('待业', '待业'), ('自由职业', '自由职业'), ('未知', '未知')], max_length=150, null=True, verbose_name='就业情况'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女'), ('未知', '未知')], max_length=30, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='name',
            field=models.CharField(max_length=150, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('微信', '微信'), ('支付宝', '支付宝'), ('银行转账', '银行转账'), ('现金', '现金'), ('未知', '未知')], max_length=100, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='source_channel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='来源渠道'),
        ),
    ]
