# Generated by Django 4.2.16 on 2025-01-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0012_alter_clientdata_deal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='支付金额'),
        ),
    ]
