# Generated by Django 4.2.16 on 2025-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0013_alter_clientdata_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='deal_status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='成交情况'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='is_employed_after_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='是否学完就业'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='sales_teacher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='就业老师'),
        ),
    ]
