# Generated by Django 4.2.16 on 2025-01-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0014_alter_clientdata_deal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='responsible_person',
            field=models.CharField(max_length=30, verbose_name='负责人'),
        ),
    ]
