# Generated by Django 4.2.16 on 2025-01-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0017_remove_clientdata_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_content', models.TextField(verbose_name='学习进度内容')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress_histories', to='closed.clientdata', verbose_name='客户')),
            ],
            options={
                'verbose_name': '学习进度历史记录',
                'verbose_name_plural': '学习进度历史记录',
            },
        ),
    ]
