# Generated by Django 4.2.16 on 2025-01-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0018_studyprogresshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_content', models.TextField(verbose_name='情况分析内容')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_analysis_histories', to='closed.clientdata', verbose_name='客户')),
            ],
            options={
                'verbose_name': '情况分析历史记录',
                'verbose_name_plural': '情况分析历史记录',
            },
        ),
        migrations.CreateModel(
            name='FollowUpRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_content', models.TextField(verbose_name='跟进记录内容')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_record_histories', to='closed.clientdata', verbose_name='客户')),
            ],
            options={
                'verbose_name': '跟进记录历史记录',
                'verbose_name_plural': '跟进记录历史记录',
            },
        ),
    ]
