# Generated by Django 4.2.16 on 2025-01-06 09:15

import closed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0019_situationanalysishistory_followuprecordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuprecordhistory',
            name='record_audio',
            field=models.FileField(blank=True, null=True, storage='closed.storages.aliyun_storages.AliyunOSSClosedAudioStorage', upload_to=closed.models.follow_up_audio_upload_path, verbose_name='通话录音'),
        ),
        migrations.AddField(
            model_name='followuprecordhistory',
            name='record_image',
            field=models.ImageField(blank=True, null=True, storage='closed.storages.aliyun_storages.AliyunOSSClosedImagesStorage', upload_to=closed.models.follow_up_image_upload_path, verbose_name='聊天截图'),
        ),
    ]
