# Generated by Django 4.2.16 on 2025-01-06 10:23

import closed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0020_followuprecordhistory_record_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprecordhistory',
            name='record_audio',
            field=models.FileField(blank=True, null=True, storage=closed.models.get_audio_storage, upload_to=closed.models.follow_up_audio_upload_path, verbose_name='通话录音'),
        ),
        migrations.AlterField(
            model_name='followuprecordhistory',
            name='record_image',
            field=models.ImageField(blank=True, null=True, storage=closed.models.get_image_storage, upload_to=closed.models.follow_up_image_upload_path, verbose_name='聊天截图'),
        ),
    ]
