# Generated by Django 4.2.16 on 2025-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0021_alter_followuprecordhistory_record_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
    ]
