# Generated by Django 4.2.16 on 2025-02-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0022_alter_clientdata_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='is_on_leave',
            field=models.BooleanField(default=False, verbose_name='是否请假'),
        ),
    ]
