# Generated by Django 4.2.16 on 2025-02-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed', '0023_clientdata_is_on_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('病假', '病假'), ('缓慢进行中（正常）', '缓慢进行中（正常）'), ('加速学习中（正常）', '加速学习中（正常）'), ('事假', '事假'), ('停滞', '停滞'), ('休学', '休学'), ('已结业C1', '已结业C1'), ('已解约', '已解约'), ('已就业C1', '已就业C1'), ('空白单元格', '空白单元格'), ('全天脱产', '全天脱产'), ('脱产转在职过程中', '脱产转在职过程中'), ('在岗人员', '在岗人员'), ('在校学生', '在校学生'), ('在职转脱产过程中', '在职转脱产过程中')], max_length=100, unique=True, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签列表',
            },
        ),
        migrations.AddField(
            model_name='clientdata',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='closed.tag', verbose_name='客户标签'),
        ),
    ]
