from .views_list import client_data_list
from .views_add_client import add_client
from .views_edit_client import update_client, delete_client
from .views_list_follow import client_data_list_follow
from .views_edit_client_follow import update_client_follow
from .views_sales_analysis import sales_analysis_view