# Generated by Django 4.2.16 on 2025-01-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(verbose_name='面试日期')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='求职者')),
                ('job_position', models.CharField(max_length=100, verbose_name='求职岗位')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='婚姻状况')),
                ('has_sales_experience', models.BooleanField(blank=True, null=True, verbose_name='是否做过销售')),
                ('initial_interviewer', models.CharField(blank=True, max_length=100, null=True, verbose_name='初试官')),
                ('final_interviewer', models.CharField(blank=True, max_length=100, null=True, verbose_name='复试官')),
                ('interview_result', models.CharField(max_length=100, verbose_name='面试结果')),
                ('rejection_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='不通过原因')),
                ('inviter', models.CharField(blank=True, max_length=100, null=True, verbose_name='邀约人')),
                ('invitation_channel', models.CharField(blank=True, max_length=100, null=True, verbose_name='邀约渠道')),
                ('is_employed', models.BooleanField(blank=True, null=True, verbose_name='是否入职')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('passed_3_day_trial', models.BooleanField(blank=True, null=True, verbose_name='是否通过3天试岗')),
                ('tracking_1_month', models.CharField(blank=True, max_length=200, null=True, verbose_name='入职1个月跟踪')),
                ('tracking_3_months', models.CharField(blank=True, max_length=200, null=True, verbose_name='入职3个月跟踪')),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人',
            },
        ),
    ]
