# Generated by Django 4.2.16 on 2025-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage='hr.storages.aliyun_storages.AliyunOSSHRStorage', upload_to='candidates/photos/', verbose_name='面试照片'),
        ),
    ]
