# Generated by Django 4.2.16 on 2025-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage='hr.storages.aliyun_storages.get_aliyun_storage', upload_to='candidates/photos/', verbose_name='面试照片'),
        ),
    ]
