# Generated by Django 4.2.16 on 2025-01-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_candidate_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
    ]
