# Generated by Django 5.1.1 on 2024-10-06 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('education', models.CharField(choices=[('大专以下', '大专以下'), ('大专', '大专'), ('本科', '本科'), ('研究生及以上', '研究生及以上'), ('未知', '未知')], default='大专', max_length=20, verbose_name='学历')),
                ('major_category', models.CharField(choices=[('IT', 'IT'), ('非IT', '非IT'), ('未知', '未知')], default='IT', max_length=10, verbose_name='专业类别')),
                ('status', models.CharField(choices=[('在职', '在职'), ('待业', '待业'), ('未知', '未知')], default='待业', max_length=15, verbose_name='状态')),
                ('address', models.CharField(max_length=255, verbose_name='就业意向城市')),
                ('city', models.CharField(default='Default City', max_length=255, verbose_name='当前所在城市')),
                ('intention', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高'), ('未知', '未知')], default='低', max_length=20, verbose_name='意向程度')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否成交')),
                ('is_invited', models.BooleanField(default=False, verbose_name='是否邀约')),
                ('is_joined', models.BooleanField(default=False, verbose_name='是否入群')),
                ('data_source', models.CharField(choices=[('AI数据', 'AI数据'), ('视频号', '视频号'), ('其他', '其他')], default='ai', max_length=100, verbose_name='数据来源')),
                ('attended_first_live', models.BooleanField(default=False, verbose_name='参加第一天直播')),
                ('attended_second_live', models.BooleanField(default=False, verbose_name='参加第二天直播')),
                ('first_day_watch_duration', models.IntegerField(default=0, verbose_name='第一天观看时长')),
                ('second_day_watch_duration', models.IntegerField(default=0, verbose_name='第二天观看时长')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='客户描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户列表',
            },
        ),
    ]
