# Generated by Django 5.1.1 on 2024-10-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name='是否接通'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_wechat_added',
            field=models.BooleanField(default=False, verbose_name='是否加微信'),
        ),
    ]
