# Generated by Django 5.1.1 on 2024-10-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_contacted_customer_is_wechat_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='additional_students',
            field=models.IntegerField(default=0, verbose_name='马甲加学员数量'),
        ),
        migrations.AddField(
            model_name='customer',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_14_days_checked',
            field=models.BooleanField(default=False, verbose_name='14天成交'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_14_days_text',
            field=models.TextField(blank=True, null=True, verbose_name='14天成交说明'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_21_days_checked',
            field=models.BooleanField(default=False, verbose_name='21天成交'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_21_days_text',
            field=models.TextField(blank=True, null=True, verbose_name='21天成交说明'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_7_days_checked',
            field=models.BooleanField(default=False, verbose_name='7天成交'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_7_days_text',
            field=models.TextField(blank=True, null=True, verbose_name='7天成交说明'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_day_feedback',
            field=models.CharField(choices=[('满意', '满意'), ('一般', '一般'), ('不考虑', '不考虑')], default='一般', max_length=20, verbose_name='第一天观后感觉'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_course_reminder',
            field=models.BooleanField(default=False, verbose_name='是否到课提醒'),
        ),
        migrations.AddField(
            model_name='customer',
            name='persona_chat',
            field=models.BooleanField(default=False, verbose_name='是否进行人设聊天'),
        ),
        migrations.AddField(
            model_name='customer',
            name='second_day_feedback',
            field=models.CharField(choices=[('满意', '满意'), ('一般', '一般'), ('不考虑', '不考虑')], default='一般', max_length=20, verbose_name='第二天观后感觉'),
        ),
        migrations.AddField(
            model_name='customer',
            name='student_batch',
            field=models.IntegerField(default=0, verbose_name='期期学员'),
        ),
        migrations.AddField(
            model_name='customer',
            name='survey_options',
            field=models.JSONField(default=list, verbose_name='多选问卷'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wechat_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='客户微信名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='data_source',
            field=models.CharField(choices=[('AI数据', 'AI数据'), ('视频号', '视频号'), ('其他', '其他')], default='AI数据', max_length=100, verbose_name='数据来源'),
        ),
    ]
