# Generated by Django 5.1.1 on 2024-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_additional_students_customer_comments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_students',
            field=models.BooleanField(default=False, verbose_name='是否有马甲加学员'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comments_count',
            field=models.BooleanField(default=False, verbose_name='是否有评论'),
        ),
    ]
