# Generated by Django 5.1.1 on 2024-10-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_additional_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cloud_computing_promotion_content',
            field=models.JSONField(default=list, verbose_name='云计算推广内容'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_needs_analysis',
            field=models.JSONField(default=list, verbose_name='客户挖需分析'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_personality_analysis',
            field=models.JSONField(default=list, verbose_name='客户性格分析'),
        ),
    ]
