# Generated by Django 5.1.1 on 2024-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_student_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cloud_computing_promotion_content',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='云计算推广内容'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_needs_analysis',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='客户挖需分析'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_personality_analysis',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='客户性格分析'),
        ),
    ]
