# Generated by Django 5.1.1 on 2024-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_cloud_computing_promotion_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='未知', max_length=100, verbose_name='姓名'),
        ),
    ]
