# Generated by Django 5.1.1 on 2024-10-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='student_batch',
            field=models.CharField(default='0', max_length=20, verbose_name='期期学员'),
        ),
    ]
