# Generated by Django 5.1.1 on 2024-11-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='supervisor_comments',
            field=models.TextField(blank=True, null=True, verbose_name='主管点评'),
        ),
    ]
