# Generated by Django 5.1.1 on 2024-11-10 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_supervisor_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='student_batch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='期期学员'),
        ),
    ]
