# Generated by Django 4.2.16 on 2024-11-24 11:28

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=customers.models.customer_audio_upload_path, verbose_name='客户音频文件'),
        ),
    ]
