# Generated by Django 4.2.16 on 2024-11-25 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recordings/%Y/%m/%d/', verbose_name='录音文件')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='录音时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '录音',
                'verbose_name_plural': '录音记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
