# Generated by Django 4.2.16 on 2024-12-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customer_city_alter_customer_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='supervisor_comments',
            field=models.TextField(blank=True, null=True, verbose_name='产品经理反馈'),
        ),
    ]
