# Generated by Django 4.2.16 on 2024-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_supervisor_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_manager_contact',
            field=models.CharField(default='未分配', max_length=20, verbose_name='产品经理对接人'),
        ),
    ]
