# Generated by Django 4.2.16 on 2024-12-11 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0017_customer_product_manager_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_created', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
