# Generated by Django 4.2.16 on 2024-12-16 06:34

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to=customers.models.customer_audio_upload_path, verbose_name='录音文件'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='录音时间'),
        ),
    ]
