# Generated by Django 4.2.16 on 2024-12-29 04:12

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_customer_customer_level_customer_discuss_checked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-created_at'], 'verbose_name': '录音/截图', 'verbose_name_plural': '录音/截图记录'},
        ),
        migrations.AddField(
            model_name='recording',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage='customers.storages.storages.CustomerImagesOSSStorage', upload_to=customers.models.customer_image_upload_path, verbose_name='聊天记录截图'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(storage='customers.storages.storages.CustomerAudioOSSStorage', upload_to=customers.models.customer_audio_upload_path, verbose_name='录音文件'),
        ),
    ]
