# Generated by Django 4.2.16 on 2024-12-29 04:43

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_alter_recording_options_recording_image_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-created_at'], 'verbose_name': '录音与图片记录', 'verbose_name_plural': '录音与图片记录'},
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(storage=customers.models.get_audio_storage, upload_to='customer_audio/', verbose_name='录音文件'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage=customers.models.get_image_storage, upload_to='customer_images/', verbose_name='图片文件'),
        ),
    ]
