# Generated by Django 4.2.16 on 2024-12-29 07:26

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_alter_recording_options_alter_recording_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=customers.models.get_audio_storage, upload_to='customer_audio/', verbose_name='录音文件'),
        ),
    ]
