# Generated by Django 4.2.16 on 2025-01-26 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0023_alter_recording_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_description', models.TextField(verbose_name='旧描述')),
                ('new_description', models.TextField(verbose_name='新描述')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_history', to='customers.customer', verbose_name='客户')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '描述修改历史',
                'verbose_name_plural': '描述修改历史',
                'ordering': ['-modified_at'],
            },
        ),
    ]
