# Generated by Django 4.2.16 on 2025-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_descriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('A', 'A 等级'), ('B', 'B 等级'), ('C', 'C 等级'), ('未知', '未知')], default='未知', max_length=10, verbose_name='客户等级'),
        ),
    ]
