# Generated by Django 4.2.16 on 2025-01-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(verbose_name='序号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('position', models.CharField(max_length=100, verbose_name='岗位')),
                ('id_card_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='联系电话')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='学历')),
                ('native_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='婚姻状况')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('seniority_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='工龄/天数')),
                ('current_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='现居地址')),
                ('labor_contract_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='劳动合同类型')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('status', models.CharField(choices=[('在职', '在职'), ('离职', '离职')], max_length=20, verbose_name='状态')),
                ('last_working_day', models.DateField(blank=True, null=True, verbose_name='最后工作日日期')),
                ('resignation_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='离职原因')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'ordering': ['serial_number'],
            },
        ),
    ]
