# Generated by Django 4.2.16 on 2025-01-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['entry_date'], 'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='serial_number',
        ),
    ]
