# Generated by Django 4.2.16 on 2024-12-31 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesuser',
            name='assistant_leader',
            field=models.ForeignKey(blank=True, help_text='为助教分配一个助教管理.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name='助教管理'),
        ),
        migrations.AddField(
            model_name='salesuser',
            name='sales_super_admin',
            field=models.ForeignKey(blank=True, help_text='为组长分配一个销售超级管理.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to=settings.AUTH_USER_MODEL, verbose_name='销售超级管理'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('group_leader', '组长'), ('sales_super_admin', '销售超级管理'), ('admin', '管理员'), ('assistant', '助教'), ('assistant_leader', '助教管理')], default='user', max_length=50, verbose_name='用户角色'),
        ),
    ]
