# Generated by Django 4.2.16 on 2025-01-02 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesuser_assistant_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesuser',
            name='hr_manager',
            field=models.ForeignKey(blank=True, help_text='为人事分配一个人事主管.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_team', to=settings.AUTH_USER_MODEL, verbose_name='人事主管'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('group_leader', '组长'), ('sales_super_admin', '销售超级管理'), ('admin', '管理员'), ('assistant', '助教'), ('assistant_leader', '助教管理'), ('hr', '人事'), ('hr_manager', '人事主管')], default='user', max_length=50, verbose_name='用户角色'),
        ),
    ]
