# Generated by Django 4.2.16 on 2025-01-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesuser_hr_manager_alter_salesuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户列表'},
        ),
    ]
