# Generated by Django 4.2.16 on 2025-01-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesuser',
            name='status',
            field=models.CharField(choices=[('active', '在职'), ('inactive', '离职')], default='active', help_text='标记用户是当前在职还是离职', max_length=20, verbose_name='用户状态'),
        ),
    ]
